version: '3.5' 

services: 
    redis: 
      image: redis
      ports: 
        - 6379:6379

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=nicolai
        - POSTGRES_PASSWORD=secret    

    frontend: 
      image: ex110
      build: ../exercise1.10
      ports: 
        - 5000:5000
      environment: 
        - API_URL=http://localhost:8000

    backend: 
      image: ex111
      build: ../exercise1.11
      ports: 
       - 8000:8000
      environment: 
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=nicolai
        - DB_PASSWORD=secret
        - DB_NAME=nicolai
        - DB_HOST=db        
      volumes:
        - vol-ex26:/usr/app
      restart: unless-stopped  


volumes:
  vol-ex26:

